# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18bb69557e26569a53c36054da0b0accd05adfa8e94788956b7774a1cea1d96878c9f2bdcaf92d5eac0731fee69eddec3ce436ab051651f7e0e2a28014ca3100

test:
  secret_key_base: f2712f32e3df80ab038ae2f39ee0b5bc93f0b530b99b590d92414e6376a46365b84d25a1e436642937bc52de6dc079f07519b154d7e691414a7d9e90a74ac0d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
